window.APP_CONFIG = {
  i18n: {
    en: {
      pageTitle: 'Awesome 3D Printing Atlas',
      subtitle: 'A dense and practical map of the 3D printing ecosystem.',
      searchLabel: 'Search',
      sectionLabel: 'Section',
      sortLabel: 'Sort',
      tagLabel: 'Tag',
      levelLabel: 'Level',
      typeLabel: 'Printer Type',
      allSections: 'All sections',
      allTags: 'All tags',
      allLevels: 'All levels',
      allTypes: 'All types',
      sourceBadge: 'Data: awesome-3d-printing (GitHub)',
      open: 'Open',
      noDescription: 'Description is not provided in the source list.',
      translatedFrom: 'Original EN',
      toolbar: {
        favorites: 'Favorites', history: 'History', random: 'Random Tool', beginner: 'Beginner Mode',
        exportMd: 'Export MD', exportJson: 'Export JSON', exportPdf: 'Export PDF', importFav: 'Import Fav', exportFav: 'Export Fav',
      },
      extra: { checkLinks: 'Check Links', suggest: 'Suggest Resource', lastUpdated: 'Updated', quickPresets: 'Quick presets' },
      cardActions: { fav: 'Fav', unfav: 'Unfav', cmp: 'Cmp', delCmp: 'DelCmp', link: 'Link', report: 'Report broken link' },
      stats: { sections: 'Sections', items: 'Resources', visible: 'Visible', fav: 'Favorites' },
      sort: { relevance: 'Relevance', az: 'A-Z', popularity: 'Popularity', updated: 'Recently updated' },
    },
    ru: {
      pageTitle: 'Атлас 3D-печати', subtitle: 'Плотная и практичная карта экосистемы 3D-печати.',
      searchLabel: 'Поиск', sectionLabel: 'Раздел', sortLabel: 'Сортировка', tagLabel: 'Тег', levelLabel: 'Уровень', typeLabel: 'Тип принтера',
      allSections: 'Все разделы', allTags: 'Все теги', allLevels: 'Любой уровень', allTypes: 'Любой тип',
      sourceBadge: 'Данные: awesome-3d-printing (GitHub)', open: 'Открыть', noDescription: 'В исходном списке описание не указано.', translatedFrom: 'Оригинал EN',
      toolbar: {
        favorites: 'Избранное', history: 'История', random: 'Случайный инструмент', beginner: 'Режим новичка',
        exportMd: 'Экспорт MD', exportJson: 'Экспорт JSON', exportPdf: 'Экспорт PDF', importFav: 'Импорт избранного', exportFav: 'Экспорт избранного',
      },
      extra: { checkLinks: 'Проверить ссылки', suggest: 'Предложить ресурс', lastUpdated: 'Обновлено', quickPresets: 'Быстрые пресеты' },
      cardActions: { fav: 'В избранное', unfav: 'Убрать', cmp: 'Сравнить', delCmp: 'Убрать cmp', link: 'Ссылка', report: 'Сообщить о битой ссылке' },
      stats: { sections: 'Разделов', items: 'Ресурсов', visible: 'Показано', fav: 'Избранное' },
      sort: { relevance: 'Релевантность', az: 'A-Я', popularity: 'Популярность', updated: 'Сначала новое' },
    },
    de: {
      pageTitle: '3D-Druck Atlas', subtitle: 'Eine dichte und praktische Karte des 3D-Druck-Ökosystems.',
      searchLabel: 'Suche', sectionLabel: 'Bereich', sortLabel: 'Sortierung', tagLabel: 'Tag', levelLabel: 'Level', typeLabel: 'Druckertyp',
      allSections: 'Alle Bereiche', allTags: 'Alle Tags', allLevels: 'Alle Level', allTypes: 'Alle Typen',
      sourceBadge: 'Daten: awesome-3d-printing (GitHub)', open: 'Öffnen', noDescription: 'In der Quellliste ist keine Beschreibung vorhanden.', translatedFrom: 'Original EN',
      toolbar: {
        favorites: 'Favoriten', history: 'Verlauf', random: 'Zufälliges Tool', beginner: 'Anfänger-Modus',
        exportMd: 'Export MD', exportJson: 'Export JSON', exportPdf: 'Export PDF', importFav: 'Favoriten importieren', exportFav: 'Favoriten exportieren',
      },
      extra: { checkLinks: 'Links prüfen', suggest: 'Ressource vorschlagen', lastUpdated: 'Aktualisiert', quickPresets: 'Schnellfilter' },
      cardActions: { fav: 'Favorit', unfav: 'Entfernen', cmp: 'Vergleich', delCmp: 'Cmp löschen', link: 'Link', report: 'Defekten Link melden' },
      stats: { sections: 'Bereiche', items: 'Ressourcen', visible: 'Sichtbar', fav: 'Favoriten' },
      sort: { relevance: 'Relevanz', az: 'A-Z', popularity: 'Popularität', updated: 'Zuletzt aktualisiert' },
    },
  },
};
